# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false
    config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

    # Configure VM settings for servers running in VirtualBox.
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end

    # Application server 1.
    config.vm.define "app1" do |app|
        app.vm.hostname = "app1.dev"
        app.vm.box = "ubuntu/trusty64"

        app.vm.network :private_network, ip: "192.168.60.2"
        config.ssh.forward_agent = true # allow external SSH
    end
end

